varsion: 2
jobs:
  build-vue:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - qzh/master
      ignore:
        - gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "70:98:31:bb:05:fd:84:85:16:4e:2f:39:05:df:00:c5"
      - checkout
      - restore_cache:
          keys: 
            - qzh_save_dependencies
      - run:
          name: qzh-install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: qzh_save_dependencies
      - run:
          name: qzh-build
          command: yarn build
      - run:
          name: qzh Prepare shell commands
          #shell chmod +x 赋予执行权限
          command: chmod +x ./scripts/deploy.sh
      - run:
          name: Run Deploy to GitHub pages
          command: ./scripts/deploy.sh